# Generated by Django 4.0.5 on 2022-08-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('create_date',)},
        ),
    ]
