# Generated by Django 4.0.5 on 2022-07-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
